#version 430 core

in vec3 vWorldPosition;
in vec3 vWorldNormal;

layout(early_fragment_tests) in;
layout(location = 0) out vec4 fragColor;
layout(rgba16f, binding = 0) uniform image2D uWaterSurfaceDataImage;

uniform sampler2D uSceneColor;
uniform sampler2D uSceneDepth;
uniform samplerCube uPrefilteredEnvMap;
uniform bool uUseIbl;
uniform float uIblIntensity;

uniform mat4 uInvViewProj;
uniform vec3 uCameraPosition;
uniform vec3 uSunDirection;
uniform vec3 uSunColor;
uniform vec3 uSkyZenithColor;
uniform vec3 uSkyHorizonColor;
uniform vec3 uSkyGroundColor;
uniform float uWaterLevel;
uniform float uReflectionStrength;
uniform float uRefractionStrength;
uniform float uAbsorptionDistance;
uniform float uSurfaceRoughness;
uniform vec3 uShallowColor;
uniform vec3 uDeepColor;
uniform vec3 uFoamColor;
uniform float uFoamStrength;
uniform float uFoamDepth;
uniform float uWaveAmplitude;
uniform float uWaveLength;
uniform float uWaveSpeed;
uniform float uWaveChoppiness;
uniform vec2 uWaveDirection;
uniform float uWaveTime;
uniform bool uSceneIsSrgb;
uniform bool uOutputSrgb;

const float TWO_PI = 6.28318530718;

vec3 SrgbToLinear(vec3 color)
{
    return pow(max(color, vec3(0.0)), vec3(2.2));
}

vec3 LinearToSrgb(vec3 color)
{
    return pow(max(color, vec3(0.0)), vec3(1.0 / 2.2));
}

vec3 ReconstructWorld(vec2 uv, float depth)
{
    vec4 clipPosition = vec4(uv * 2.0 - 1.0, depth * 2.0 - 1.0, 1.0);
    vec4 worldPosition = uInvViewProj * clipPosition;
    return worldPosition.xyz / max(worldPosition.w, 0.00001);
}

vec3 SampleSkyReflection(vec3 direction)
{
    float height = clamp(direction.y * 0.5 + 0.5, 0.0, 1.0);
    if (height < 0.5)
    {
        float groundFactor = smoothstep(0.0, 0.5, height);
        return mix(uSkyGroundColor, uSkyHorizonColor, groundFactor);
    }
    return mix(uSkyHorizonColor, uSkyZenithColor, (height - 0.5) * 2.0);
}

vec3 ApplyMicroNormal(vec3 baseNormal, vec2 worldPosition)
{
    vec2 forward = length(uWaveDirection) > 0.001
        ? normalize(uWaveDirection)
        : vec2(1.0, 0.0);
    vec2 side = vec2(-forward.y, forward.x);
    const vec2 directions[6] = vec2[](
        vec2(1.00, 0.13),
        vec2(-0.78, 0.62),
        vec2(0.33, -0.94),
        vec2(0.91, -0.41),
        vec2(0.55, 0.83),
        vec2(-0.25, -0.97));
    const float lengthFactors[6] = float[](0.34, 0.23, 0.16, 0.105, 0.072, 0.048);
    const float amplitudeFactors[6] = float[](0.030, 0.022, 0.016, 0.011, 0.007, 0.004);
    const float speedFactors[6] = float[](1.15, 1.32, 1.49, 1.68, 1.87, 2.08);
    const float phaseOffsets[6] = float[](0.4, 2.1, 4.7, 1.6, 3.5, 5.5);

    vec2 slope = vec2(0.0);
    for (int i = 0; i < 6; ++i)
    {
        vec2 direction = normalize(
            forward * directions[i].x + side * directions[i].y);
        float wavelength = max(uWaveLength * lengthFactors[i], 0.45);
        float waveNumber = TWO_PI / wavelength;
        float phase = dot(direction, worldPosition) * waveNumber -
            uWaveTime * uWaveSpeed * speedFactors[i] + phaseOffsets[i];
        slope += direction *
            (uWaveAmplitude * amplitudeFactors[i] * waveNumber * cos(phase));
    }

    // The geometry supplies the broad normal; this low-amplitude component
    // restores the fine ripples that would otherwise require a dense mesh.
    return normalize(baseNormal + vec3(-slope.x, 0.0, -slope.y) *
        (0.65 + 0.35 * clamp(uWaveChoppiness, 0.0, 1.5)));
}

void main()
{
    vec3 normal = ApplyMicroNormal(normalize(vWorldNormal), vWorldPosition.xz);

    // This write uses the exact fragment generated by the visible ocean. The
    // early fragment tests guarantee that only fragments passing the target
    // depth test publish water metadata for the underwater pass.
    imageStore(
        uWaterSurfaceDataImage,
        ivec2(gl_FragCoord.xy),
        vec4(
            gl_FragCoord.z,
            1.0,
            normal.x * 0.5 + 0.5,
            normal.z * 0.5 + 0.5));

    vec3 viewDirection = normalize(uCameraPosition - vWorldPosition);
    float nDotV = max(dot(normal, viewDirection), 0.0);
    float fresnel = pow(1.0 - nDotV, 5.0);
    fresnel = mix(0.02, 1.0, fresnel);

    float sceneDepth = texture(uSceneDepth, gl_FragCoord.xy / vec2(textureSize(uSceneDepth, 0))).r;
    bool hasSceneSurface = sceneDepth < 0.9999;
    vec3 scenePosition = hasSceneSurface
        ? ReconstructWorld(gl_FragCoord.xy / vec2(textureSize(uSceneDepth, 0)), sceneDepth)
        : vWorldPosition + normalize(vWorldPosition - uCameraPosition) * uAbsorptionDistance;

    float waterDepth = hasSceneSurface
        ? max(vWorldPosition.y - scenePosition.y, 0.0)
        : uAbsorptionDistance * 2.0;
    waterDepth /= max(abs(dot(normal, viewDirection)), 0.2);
    float depthFactor = clamp(waterDepth / max(uAbsorptionDistance, 0.001), 0.0, 1.0);
    float transmittance = exp(-waterDepth / max(uAbsorptionDistance, 0.001));

    vec2 screenUv = gl_FragCoord.xy / vec2(textureSize(uSceneColor, 0));
    vec2 refractionUv = clamp(
        screenUv + normal.xz * uRefractionStrength * (0.25 + depthFactor * 0.75),
        vec2(0.001),
        vec2(0.999));
    vec3 scene = texture(uSceneColor, refractionUv).rgb;
    if (uSceneIsSrgb)
        scene = SrgbToLinear(scene);

    vec3 waterBodyColor = mix(uShallowColor, uDeepColor, depthFactor);
    vec3 transmittedScene = scene * transmittance;
    vec3 inScatteredWater = waterBodyColor * (1.0 - transmittance);
    vec3 refractedColor = transmittedScene + inScatteredWater;

    vec3 reflectionDirection = reflect(-viewDirection, normal);
    vec3 reflectedColor = SampleSkyReflection(reflectionDirection);
    if (uUseIbl)
    {
        float mip = clamp(uSurfaceRoughness, 0.0, 1.0) * 5.0;
        reflectedColor = textureLod(uPrefilteredEnvMap, reflectionDirection, mip).rgb;
        reflectedColor *= max(uIblIntensity, 0.0);
    }

    vec3 sunDirection = normalize(uSunDirection);
    float sunHighlight = pow(
        max(dot(reflectionDirection, sunDirection), 0.0),
        mix(96.0, 900.0, 1.0 - clamp(uSurfaceRoughness, 0.0, 1.0)));
    reflectedColor += max(uSunColor, vec3(0.0)) * sunHighlight * 0.35;

    vec3 color = mix(refractedColor, reflectedColor, fresnel * uReflectionStrength);

    float waveCrest = smoothstep(
        0.30,
        0.85,
        abs(vWorldPosition.y - uWaterLevel) / max(uWaveAmplitude, 0.001));
    float normalCrest = smoothstep(0.12, 0.48, 1.0 - normal.y);
    float shallowFoam = 1.0 - smoothstep(0.0, max(uFoamDepth, 0.001), waterDepth);
    float foam = max(waveCrest, normalCrest) * shallowFoam * uFoamStrength;
    color = mix(color, uFoamColor, clamp(foam, 0.0, 1.0));

    if (uOutputSrgb)
        color = LinearToSrgb(color);
    fragColor = vec4(max(color, vec3(0.0)), 1.0);
}
